openapi: 3.0.0
info:
  title: ModernDoc API
  description: API endpoint for ModernDoc
  version: 0.1.9
servers:
  - url: http://localhost:5000
    description: ModernDoc API

tags:
  - name: User
    description: User management
  - name: Tag
    description: Tag management
  - name: Field
    description: Field management

paths:
  /user:
    post:
      tags:
        - User
      summary: Create a new user
      operationId: createUser
      requestBody:
        description: User object that needs to be added
        required: true
        content:
          application/json:
            schema:
              properties:
                title:
                  type: string
                  description: User's title
                firstName:
                  type: string
                  description: User's first name
                lastName:
                  type: string
                  description: User's last name
                sex:
                  type: string
                  description: m,f
                birthDate:
                  type: string
                  description: User's birth date ISO String
                citizenId:
                  type: string
                  description: User's citizen id
                phoneNumber:
                  type: string
                  description: User's phone number
                password:
                  type: string
                  description: User's password
      responses:
        '201':
          description: User created
        '400':
          description: Invalid input

  /user/citizenId-status/{citizenId}:
    get:
      tags:
        - User
      summary: Check if citizen id is available
      operationId: checkCitizenId
      parameters:
        - name: citizenId
          in: path
          description: Citizen id to check
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Citizen id available
        '400':
          description: Citizen ID is not valid
        '409':
          description: Citizen id already exists

  /user/login:
    post:
      tags:
        - User
      summary: Login user
      operationId: loginUser
      requestBody:
        description: User object that needs to be added
        required: true
        content:
          application/json:
            schema:
              properties:
                phoneNumber:
                  type: string
                  description: User's phone number
                password:
                  type: string
                  description: User's password
      responses:
        '200':
          description: User logged in
        '400':
          description: User not found
        '403':
          description: Wrong Password

  /tag/create:
    post:
      tags:
        - Tag
      summary: Create a new tag
      operationId: createTag
      requestBody:
        description: Tag object that needs to be added
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  description: Tag's name
      responses:
        '201':
          description: Tag created
        '500':
          description: Tag creation failed

  /tag/get-all:
    get:
      tags:
        - Tag
      summary: Get all tags
      operationId: getTags
      responses:
        '200':
          description: Tags retrieved
        '500':
          description: Tags retrieval failed
  /tag/name/{name}:
    get:
      tags:
        - Tag
      summary: Get tag by name
      operationId: getTagByName
      parameters:
        - name: name
          in: path
          description: Tag's name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Tag retrieved
        '500':
          description: Tag retrieval failed
  /tag/id/{id}:
    get:
      tags:
        - Tag
      summary: Get tag by id
      operationId: getTagById
      parameters:
        - name: id
          in: path
          description: Tag's id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Tag retrieved
        '500':
          description: Tag retrieval failed
  /tag/edit-name:
    put:
      tags:
        - Tag
      summary: Edit tag's name
      operationId: editTagName
      requestBody:
        description: Tag object that needs to be edited
        required: true
        content:
          application/json:
            schema:
              properties:
                id:
                  type: string
                  description: Tag's id
                name:
                  type: string
                  description: Tag's name
      responses:
        '200':
          description: Tag edited
        '500':
          description: Tag edit failed
  /field:
    post:
      tags:
        - Field
      summary: Create a new field
      operationId: createField
      requestBody:
        description: Field object that needs to be added
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  description: Field's name
                officialName:
                  type: string
                  description: Field's official name
                description:
                  type: string
                  description: Field's description
                type:
                  type: string
                  description: text,number,date,singleSelect,multipleSelect
      responses:
        '200':
          description: Field created
        '500':
          description: Field creation failed
  /field/get-all:
    get:
      tags:
        - Field
      summary: Get all fields
      operationId: getFields
      responses:
        '200':
          description: Fields retrieved
        '500':
          description: Fields retrieval failed
  /field/edit-official-name:
    put:
      tags:
        - Field
      summary: Edit field's official name
      operationId: editFieldOfficialName
      requestBody:
        description: Field object that needs to be edited
        required: true
        content:
          application/json:
            schema:
              properties:
                id:
                  type: string
                  description: Field's id
                officialName:
                  type: string
                  description: Field's official name
      responses:
        '200':
          description: Field edited
        '500':
          description: Field edit failed
